test:
  REDIS_URL: 'redis://127.0.0.1:6379'
  GOOGLE_APP_ID: 'id'
  GOOGLE_APP_KEY: 'key'
  RESQUE_WEB_HTTP_BASIC_AUTH_USER: 'user'
  RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD: 'pass'
  SCRIPTMANAGE_PASSWORD: 'pass'
  ACCOUNT_TOKEN: ''

development:
  REDIS_URL: 'redis://127.0.0.1:6379'
  GOOGLE_APP_ID: 'id'
  GOOGLE_APP_KEY: 'key'
  RESQUE_WEB_HTTP_BASIC_AUTH_USER: 'user'
  RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD: 'pass'
  SCRIPTMANAGE_PASSWORD: 'pass'
  ACCOUNT_TOKEN: ''


production:
  