# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1703f5feadb717e548334812e5cb2773ce8060b49304603a68b4363a99081d1a595c2800cfb43f24287da8f8c960320fbc4e7fdefaa9b2fe4d675bd505a25dfe

test:
  secret_key_base: 312890c02a59dc142bdd1f4f330458d51829d443bf21d95a1d89f0d63e3bea7f24c2d9e51cd6cbb38b5f2f87676495f0875e147620764c153220d40ce91dce26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
